language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-27.0.3
    - platform-tools
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-27"
script: ./gradlew assembleplayDebug
group: stable
dist: trusty
os: linux