language: android

android:
  components:
    - build-tools-27.0.1
    - android-27
    - add-on
    - extra
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew

script: ./gradlew assembleplayDebug