language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    