language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - chmod +x gradlew

script: ./gradlew assembleplayDebug